### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by shouyezhe** [h-bouzid/spatr#1]
Hi, h-bouzid. Thanks for your impressive work on 3D Human Action Recognition. I was wondering if you could provide more about your release plan?

**Comment by h-bouzid** [comment]
Hi @shouyezhe , 

I've been planning to upload the code once the paper is accepted. After I clean it and make it easily runnable. 

I will try to make it available in 2-3 weeks.
Thanks 😄

**Comment by h-bouzid** [comment]
The code is now available, and the embeddings can be downloaded without the need to train the auto-encoder.
