### ISSUE TITLE
About neural3dmm.ipynb

### ISSUE THREAD

**Issue by Alextien40816291** [h-bouzid/spatr#2]
Hi, h-bouzid. Nice work on 3D Human Action Recognition. I was wondering where can I find the neural3dmm.ipynb file and set args['mode'] = 'generate' ?

**Comment by h-bouzid** [comment]
Hi, @Alextien40816291. Thank you for your interest 😄

Sorry, it appears I misnamed the file. It isn't "neural3dmm.ipynb" but rather "train.ipynb" you can find it in the "NeuralSMPL" folder.

Thank you for the question.
